### ISSUE TITLE
Unit / Meaning of "powerUsageOfDay"

### ISSUE THREAD

**Issue by dotcom84** [ReverseEngineeringDE/SAIC-API-Documentation#11]
First of all! Thanks for this fantastic project. I've been playing around with the APIs for roughly 11 months (ever since I got the ZS) - yet didn't have the time to go into all details.

For the ZS I currently use the following values:
bmsPackSOCDsp (% / 10), bmsEstdElecRng (km), fuelRangeElec (km / 10), mileageOfDay (km / 10), totalBatteryCapacity (kWh / 10), mileage (km / 10)
All of those match the car's values or my expectations. My idea is (among others) to calculate and show the daily average consumption.

However for powerUsageOfDay I have no clue how to interpret it. I was expecting the unit to be kW (after diving it by 10). However that cannot be the case: according to my logged data the car should be almost empty, but is still half full. Percentage also does not work for the same reason.

Also the power usage does not seem to correspond to the daily mileage:
- 7.12.: mileageOfDay: 18 km / powerUsageOfDay: 304
- 8.12.: mileageOfDay: 14 km / powerUsageOfDay: 46

**Comment by tisoft** [comment]
Is totalBatteryCapacity correct for the ZS? For the MG5 it is 725, which is not correct.

As for the powerUsage fields, I have no clue. They seem to be a bit random. 🤣 

I haven't found a filed, that show the accumulated power usage reliably, but I havenÄt cheched out all possible messages yet.

(I just found out, that at least for the MG5 in some message types the exterior temperature is always -128, but in other types it is correct, so maybe that is also the case for the power usage)

**Comment by dotcom84** [comment]
725 sounds correct for the long range ZS.

**Comment by tisoft** [comment]
We have splitted this project up in several subprojects under the https://github.com/SAIC-iSmart-API organization.

Please open a thread in the discussions over there, if your question/issue is still unsolved: https://github.com/orgs/SAIC-iSmart-API/discussions
