### ISSUE TITLE
java messages flooding syslog and daemon.log

### ISSUE THREAD

**Issue by stpmuspro** [ReverseEngineeringDE/SAIC-API-Documentation#43]
Installed said-java-mqtt-gateway via deb

If service is running syslog and daemon.log are flooded with all java-messages.

How to stop this kind of logging?

**Comment by mschmiedel** [comment]
Proposing this merge request as a first try to get logging into control:

https://github.com/ReverseEngineeringDE/SAIC-API-Documentation/pull/55
