### ISSUE TITLE
[Enhancement] Werte gezielt abfragen mit Zeitintervall

### ISSUE THREAD

**Issue by Tonno87** [ReverseEngineeringDE/SAIC-API-Documentation#51]
Hallo Zusammen, 

tolles Projekt! Danke für eure Arbeit :)

Ich würde mir wünschen das die configfile so erweitert wird das man z.B. nur den SOC abfragen **kann**.
Für die meisten Anwender ist dieser Wert ausreichend, der Rest ist optional. 

Auch hätte ich gerne eine Möglichkeit um die Intervalle der Abfrage zu ändern. Beim laden an der Wallbox sind meiner Meinung nach Werte von 1-2 min ausreichend. Um mit 11kw 1% zu laden dauert es länger als 2 Minuten. Daher sollte EVCC damit umgehen können.
Das erzeugt zum einen weniger Datenmüll und zum anderen wird es damit unwahrscheinlicher das die API abfragen irgendwann geblockt werden. Je mehr das Gateway benutzen desto eher wird das zum Problem werden.

Was meint ihr dazu?

**Comment by tisoft** [comment]
Einzelne Werte Abfragen geht nicht, da die API immer einen ganzen Satz von Werten liefert.
Es gibt einen API Call, der alle Charging/Power related Werte liefert und einen der den Fahrzeugzustand (Türen/GPS/Klima/Reifendruck/...) Da könnte man natürlich nur den Charging Call machen, wenn man nur den SOC haben möchte.
Das Problem dabei ist, dass die API immer nur eine Verbindung zu lässt, also wenn man hierüber den SOC ausliest, wird man aus der iSmart App geschmissen und kann dann nicht mehr deren Funktionen nutzen. Daher versuche ich die MQTT Anbindung so zu bauen, dass alle Features abgebildet werden können aber gleichzeitig möchte ich da nicht zu viele Optionen zum Konfigurieren haben, um den Code nicht zu kompliziert werden zu lassen.
Die Frequenz will ich aber konfigurierbar machen, da gibt es in https://github.com/ReverseEngineeringDE/SAIC-API-Documentation/issues/46 einen 1. Vorschlag, wie das aussehen könnte.

Wenn du wirklich nur den SOC brauchst, dann könntest du dir https://github.com/ReverseEngineeringDE/SAIC-API-Documentation/tree/main/saic-java-api-gateway ansehen. Der wrapped die API calls nach JSON, macht aber keine Aktualisierungen von sich aus. Für den SOC würde das reichen.

**Comment by Tonno87** [comment]
Ah okay dann findet das mit den häufigen Abfragen nur bei MQTT statt? Dann werde ich das andere mal ausprobieren.

Ich stimme dir natürlich zu das man eine Lösung braucht um nicht immer wieder zwischen App und Gateway zu wechseln. Solange aber die Heizung usw. nicht eingeschaltet werden kann beschränke ich mich persönlich auf den SOC. Dann muss ich nur wechseln wenn an der Wallbox geladen wurde. Das müssen wir zum Glück nicht jeden Tag.

Wenn das Projekt soweit ist das man über Home Assistant sowohl abfragen als auch Steuern kann ist die App auch nicht mehr notwendig. Aber ich vermute das dauert noch etwas :)

Ich kann leider so Ad-Hoc nichts zum Projekt beitragen um euch zu helfen, meine Kenntnisse bei Programmiersprachen beschränken sich auf C. Selbst da auch nur das nötigste um Mikrocontroller zu steuern. Java ist an mir vorbei gegangen...

**Comment by tisoft** [comment]
We have splitted this project up in several subprojects under the https://github.com/SAIC-iSmart-API organization.

Please open a thread in the discussions over there, if your question/issue is still unsolved: https://github.com/orgs/SAIC-iSmart-API/discussions
