### ISSUE TITLE
Mixed success

### ISSUE THREAD

**Issue by ffrog8** [ReverseEngineeringDE/SAIC-API-Documentation#56]
Trying to use the ismart-api-cli username password I initially get a `The account is not registered.` response. After some looking around I notice that the app mentioned in the Getting Started section is for .europe and the app I have on my phone is .au - So I try modifying the endpoint URL to https://tap-au.soimt.com/... which gives me a different error message `Incorrect password. You may have another 4 attempts of the day, please try again.` 

I have verified via java debugger that the password is correct (albeit complicated).

Has anyone had success with a non .europe account?
Has anyone had success with a complex password?

Cheers!

**Comment by tisoft** [comment]
The ismart app filters out some characters from passwords. So the password send to the backend may not be the one you actually entered. I have not implemented the same filtering algorithm, so I send the exact password, you specify. Could you try to change your password in the official app to something without special characters?

Regarding non-europe accounts. I know of no-one to have tried it yet (Except you 😄). If you manage to get it working with your password, I will gladly make the endpoint URL configurable. I can't test it myself for obvious reasons 😎.

**Comment by ffrog8** [comment]
Okay - I got it to work, your tip RE filtering the password (to alpha numeric) was the reason for success. Turns out I can't change my password (i guess because the app doesn't filter the password during the validate step of changing your password - i guess i have to manually filter it to change it? :rofl:)

I get a bunch of output, with 26 `The remote control instruction failed, please try again later.` and a final output with a bunch of vehicle stats. That feels like success.

Cheers!

**Comment by ffrog8** [comment]
More success - I got MQTT up and running by adding the filtering to the password `applicationData.setPassword(saicPassword.replaceAll("[^A-Za-z0-9]", ""));` and specifying the SAIC URI. 
The MQTT does poll quite often - is there any 12V battery concerns?

Cheers!

**Comment by tisoft** [comment]
The mqtt Gateway stops polling 10 minutes after the engine is shut out and the car is not charging anymore. As soon as the car starts, the car actively sends a engine start notification, which wakes up the mqtt poller. 

I have this running since October and have no problems with draining the 12v battery. But your ~~mileage~~ _voltage_ may vary. 🤓

_Originally posted by @tisoft in https://github.com/ReverseEngineeringDE/SAIC-API-Documentation/issues/13#issuecomment-1455060783_

**Comment by tisoft** [comment]
We have splitted this project up in several subprojects under the https://github.com/SAIC-iSmart-API organization.

Please open a thread in the discussions over there, if your question/issue is still unsolved: https://github.com/orgs/SAIC-iSmart-API/discussions
