### ISSUE TITLE
Help to read MG4 Trophy figures

### ISSUE THREAD

**Issue by adamcable** [ReverseEngineeringDE/SAIC-API-Documentation#57]
Hi everyone,

This is a great project! It worked first time using the CLI - but I'm having issues reading the numbers returned.
I'm just after the current charge level. I've attached a screenshot from the MG app showing 60% charge, and the JSON returned from running the JAR. I can see "bmsPackSOCDsp":1023 but I'm unsure how that relates, or how to convert it.
Can anyone shed any light for me? Thank you :)

Adam
[mg4.txt](https://github.com/ReverseEngineeringDE/SAIC-API-Documentation/files/10928697/mg4.txt)
![mg4](https://user-images.githubusercontent.com/3158860/223946968-4d756b10-5a01-476f-9e8d-4e9725f104a1.jpg)

**Comment by adamcable** [comment]
Wow, what a quick reply @tisoft - thank you.
More than happy to help out debug in whatever way is useful!

**Comment by adamcable** [comment]
I've gone for the (most probably awful) assumption that for some unknown reason they've used the same km->miles conversion but for state of charge - at least it gives me a relatively accurate result for now.
I'll charge the car sometime and see if it still works out!

**Comment by yagamosh** [comment]
I doubt it has anything to do with miles or km. I experience the same issue in the response for my MG Marvel R and where I am (Sweden) we use km. I am using the mqtt gateway and this 102.3% value is quickly replaced with the correct percentage, it still shows up though.

**Comment by adamcable** [comment]
Was also thinking it might need another poll a few seconds later as these may be placeholder values.

**Comment by adamcable** [comment]
Just FYI - charged the car up to 80% overnight and the bmsPackSOCDsp, realtimePower & totalBatteryCapacity values are all identical

**Comment by adamcable** [comment]
Have also tried sleeping between chargingStatusResponseMessage.getApplicationData() calls, and waiting 10 seconds to see if the data has changed, but no joy

**Comment by adamcable** [comment]
Happy to share MITM debug calls from the app, or my credentials if that'd help get this working for lots of other users.

**Comment by tisoft** [comment]
We have splitted this project up in several subprojects under the https://github.com/SAIC-iSmart-API organization.

Please open a thread in the discussions over there: https://github.com/orgs/SAIC-iSmart-API/discussions
