### ISSUE TITLE
How to install and config the mqtt 

### ISSUE THREAD

**Issue by Tonio16** [ReverseEngineeringDE/SAIC-API-Documentation#58]
Hello

Would it be possible to have a how-to for the mqtt if we are not using home assistant?

I installed the docker based on the link given on the GitHub but I don't find the configuration file in the etc folder. And I have no idea of what should be configured in this file.

Tx

Antoine

**Comment by tisoft** [comment]
We have splitted this project up in several subprojects under the https://github.com/SAIC-iSmart-API organization.

Please open a thread in the discussions over there: https://github.com/orgs/SAIC-iSmart-API/discussions
